#if defined _gg_message_included
 #endinput
#endif
#define _gg_message_included

#define PREFIX "[Gravity gun] "

#define PARAMETER_VALUE_MAX_SIZE 16

#define PARAMETER_TRACE_MODE "Trace mode"
#define PARAMETER_CAPTURE_MODE "Capture mode"
#define PARAMETER_DISTANCE "Distance"
#define PARAMETER_SPEED_FACTOR "Speed factor"
#define PARAMETER_THROW_SPEED "Throw speed"
#define PARAMETER_CONE_ANGLE "Cone angle"
#define PARAMETER_CONE_DISTANCE "Cone distance"
